name: cinemapedia
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  analyzer: ^5.13.0
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.3
  flutter_riverpod: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^6.0.9
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/cinemapedia-logo.png
    - assets/cinemapedia-splash.png
    - assets/cinemapedia-title.png

flutter_native_splash:
  color: "#000000"
  image: assets/cinemapedia-splash.png
  android: true
  ios: true
  web: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/cinemapedia-logo.png"
